remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: SimpleX-Themes
description: SimpleX Chat Theme Archive

# Ensure Jekyll serves all files
include:
  - screenshots
  - resources

# Giscus configuration
giscus:
  repo_id: "R_kgDOMoOy9A"
  category: "General"
  category_id: "DIC_kwDOMoOy9M4CvYxA"