base: "BLACK"
colors:
  accent: "#ffa5df19"
  accentVariant: "#ff1a5a32"
  secondary: "#ff1c8f1d"
  secondaryVariant: "#ff184908"
  background: "#ff113339"
  menus: "#ff051e0e"
  title: "#ff1f8c4b"
  accentVariant2: "#ffffb300"
  sentMessage: "#ff113339"
  sentReply: "#ff113339"
  receivedMessage: "#ff113339"
  receivedReply: "#ff113339"
wallpaper:
  preset: "flowers"
  scale: 2.0
  background: "#ff113339"
  tint: "#ff31560d"