name: Generate popularity

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  discussions: read
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Generate popularity
        run: node scripts/generate-popularity.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated stats
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add data/popular.json

          git diff --cached --quiet && exit 0

          git commit -m "Update popularity stats"
          git push